### ISSUE TITLE
How lastest for package version works over time?

### ISSUE THREAD

**Issue by efleurine** [CuistotduCoin/front#1]
Thanks for such great sharing.

I have one question regarding your package.json. I saw you use *latest* for everything regarding the package version of the dependencies. 

Is it ok; like with no incompatibility problems while some packages are being updated faster than others.

Thanks

**Comment by romainquellec** [comment]
Je réponds en français, tu as l'air francophone.
"Is it ok" Non, ne pas faire ça sur un gros projet, faut mieux figer les packages.
C'est en prod en ce moment, mais a terme, je fixerai les versions des différents packages.
